### ISSUE TITLE
CM13: only position independent executables (PIE) are supported.

### ISSUE THREAD

**Issue by pyc0de** [cernekee/dnsproxy2#3]
When trying to run dnsproxy2 on CM13:
error: only position independent executables (PIE) are supported.

**Comment by cernekee** [comment]
You can try setting `APP_PLATFORM := 16` in Application.mk, per:

http://stackoverflow.com/questions/24818902/running-a-native-library-on-android-l-error-only-position-independent-executab

**Comment by pyc0de** [comment]
thanks
but could you include buit binaries for APP_PLATFORM := 16 along side with older version binaries for people who don't know how to build/don't have capability.
Much appreciated.
